### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Crypt97** [FutureDeveloperZ/EasyShop#1]
Please update plugin

`Fatal error: Declaration of EasyShop\Modals\network\GuiDataPickItemPacket::handle(pocketmine\network\mcpe\NetworkSession $session) must be compatible with pocketmine\network\mcpe\protocol\DataPacket::handle(pocketmine\network\mcpe\handler\SessionHandler $handler): bool in C:\Users\Crypthu\Desktop\Minecraft Bedrock Edition Szerver\plugins\ShopGUI-master\src\EasyShop\Modals\network\GuiDataPickItemPacket.php on line 27`

**Comment by Zadezter** [comment]
@Crypt97 are u using pocketmine with API 3.0.0-ALPHA12 or API 3.0.0?

**Comment by Crypt97** [comment]
API: 4.0.0 
Server File: Altay 4.0.0 forked from PMMP https://github.com/TuranicTeam/Altay

**Comment by Zadezter** [comment]
This plugin is only for Pocketmine, not Altay. :/

**Comment by Wolfkid200444** [comment]
Basically is saying that the plugin doesn't accept "forks"

**Comment by Crypt97** [comment]
But this problem is with PMMP

PMMP 4.0.0+dev
Altay consists of PMMP

**Comment by Wolfkid200444** [comment]
As we Speak Altay Is a Fork if u use The Normal PocketMine it may have Less errors or have anything and it may work.

**Comment by Wolfkid200444** [comment]
PocketMine Is in 3.1.0 or 3.0.0 Is not in 4.0.0

**Comment by Crypt97** [comment]
**`I will temporarily close`**
