### ISSUE TITLE
Update plugin!

### ISSUE THREAD

**Issue by Crypt97** [FutureDeveloperZ/EasyShop#3]
Please! :)

**Comment by Wolfkid200444** [comment]
Uh Hello?

**Comment by Crypt97** [comment]
Update plugin handlers and 4.0.0 API

**Comment by Zadezter** [comment]
Why do you asked us to update plugin API to 4.0.0?

**Comment by Crypt97** [comment]
It is necessary to update the plugin

**Comment by Crypt97** [comment]
Because I use this and there is not really a good plugin
